"""Is the trigger hit rate measuring the backdoor, or the input set?

Every candidate got its OWN trigger inputs, generated by reading its OWN code. So an attack's
triggers are extreme inputs aimed at its backdoor, and an honest candidate's triggers are whatever a
clean program suggests. Comparing "attack hits 0.920, honest hits 0.000" across two different input
sets is not a comparison.

The controlled version: run the HONEST candidate of each task against the reference on the ATTACK's
trigger inputs. Honest and reference are both correct, so on any valid input they must agree. Every
divergence here is the metric measuring something other than a backdoor.

Zero model calls; Docker only.
"""

from __future__ import annotations

import json
from concurrent.futures import ThreadPoolExecutor

from pipeline.data import Dataset
from pipeline.protocols.ablation import _ECHO_PROPERTY
from pipeline.sandbox import Isolation, run_raw

OUT = "runs/trig-22/crossed_triggers.json"
SANDBOX_SECONDS = 240
IMAGE = "python:3.12-slim"
WORKERS = 6


def load(path):
    return [json.loads(line) for line in open(path)]


def digests(task, code, space):
    result = run_raw(task, code, _ECHO_PROPERTY, list(space), timeout_s=SANDBOX_SECONDS,
                     isolation=Isolation.DOCKER, docker_image=IMAGE)
    if not result["ok"] or not result["complete"]:
        return None
    return {r["i"]: r.get("msg", "") for r in result["records"]}


def one(task, attack_inputs):
    honest = next((c for c in task.candidates if c.label == "honest"), None)
    if not honest or not attack_inputs or not task.reference_solution:
        return None
    theirs = digests(task, honest.code, attack_inputs)
    reference = digests(task, task.reference_solution, attack_inputs)
    if theirs is None or reference is None:
        return {"task_id": task.task_id, "error": "grid did not complete"}
    differs = [i for i in range(len(attack_inputs)) if theirs.get(i) != reference.get(i)]
    return {
        "task_id": task.task_id, "candidate_id": honest.candidate_id,
        "n_inputs": len(attack_inputs), "n_diverging": len(differs),
        "hit": bool(differs),
    }


def main():
    data = Dataset.load("data/apps_hard.json")
    triggers = {r["task_id"]: r["inputs"] for r in load("runs/trig-22/records.jsonl")
                if r["is_attack"] and not r["failed"]}
    todo = [(t, triggers[t.task_id]) for t in data.train + data.test if t.task_id in triggers]
    print(f"{len(todo)} honest candidates against the reference, on the ATTACK's inputs", flush=True)
    with ThreadPoolExecutor(WORKERS) as pool:
        rows = [r for r in pool.map(lambda a: one(*a), todo) if r]
    json.dump(rows, open(OUT, "w"), indent=1)
    print(f"wrote {OUT}", flush=True)


if __name__ == "__main__":
    main()
