import collections
from hypothesis import given, settings, strategies as st
import random # Required for seeding, not for generating test inputs
from candidate import task_func

# Constants from the problem description
LETTERS = ['a', 'b', 'c', 'd', 'e']

@settings(max_examples=50, deadline=None)
@given(string_length=st.integers(min_value=0, max_value=12))
def test_output_structure_and_sum_of_frequencies(string_length):
    """
    SPEC BASIS: "Returns: - collections.OrderedDict: An ordered dictionary where keys are letters and values are their frequencies..."
                "count the frequency of each letter"
    PROPERTY: The result is an OrderedDict. All keys are single characters from LETTERS. All values are non-negative integers.
              The sum of all frequencies (values) must equal the input string_length.
    STRATEGY: Test with string_length from 0 to 12. This covers the empty string, single-character string,
              and small strings, where counting errors or incorrect dictionary construction are likely to manifest.
    """
    random.seed(0) # Ensure reproducibility for internal random string generation
    try:
        result = task_func(string_length)
    except Exception:
        result = None

    assert result is not None, f"task_func raised an exception for string_length={string_length}"
    assert isinstance(result, collections.OrderedDict), f"Expected OrderedDict, got {type(result)}"

    total_frequency = 0
    for key, value in result.items():
        assert isinstance(key, str) and len(key) == 1, f"Key '{key}' is not a single character string"
        assert key in LETTERS, f"Key '{key}' is not in the predefined LETTERS list"
        assert isinstance(value, int) and value >= 0, f"Value '{value}' for key '{key}' is not a non-negative integer"
        total_frequency += value

    assert total_frequency == string_length, \
        f"Sum of frequencies ({total_frequency}) does not match string_length ({string_length})"

@settings(max_examples=50, deadline=None)
@given(string_length=st.integers(min_value=0, max_value=12))
def test_descending_frequency_order(string_length):
    """
    SPEC BASIS: "...sorted by frequency in descending order."
    PROPERTY: The values (frequencies) in the OrderedDict must be in non-increasing order.
    STRATEGY: Test with string_length from 0 to 12. Small lengths allow for a wider variety of frequency
              distributions to be generated by chance, including cases with ties or highly skewed distributions,
              targeting the sorting logic.
    """
    random.seed(0) # Ensure reproducibility for internal random string generation
    try:
        result = task_func(string_length)
    except Exception:
        result = None

    assert result is not None, f"task_func raised an exception for string_length={string_length}"

    if not result: # Empty dict for string_length=0 or if no letters appeared
        return

    previous_frequency = float('inf')
    for frequency in result.values():
        assert frequency <= previous_frequency, \
            f"Frequencies are not in descending order: {list(result.values())}"
        previous_frequency = frequency

@settings(max_examples=50, deadline=None)
@given(string_length=st.integers(min_value=0, max_value=12))
def test_determinism_with_seed(string_length):
    """
    SPEC BASIS: The example uses `random.seed(0)` and shows a specific output, implying deterministic behavior.
    PROPERTY: For a given string_length and `random.seed` value, task_func should always produce the exact same output.
    STRATEGY: Call task_func twice with the same string_length, ensuring `random.seed` is set before each call.
              Compare the outputs for exact equality. This catches implementations that use non-seeded randomness
              or have stateful side effects.
    """
    # First call
    random.seed(0)
    try:
        result1 = task_func(string_length)
    except Exception:
        result1 = None

    # Second call
    random.seed(0)
    try:
        result2 = task_func(string_length)
    except Exception:
        result2 = None

    assert result1 is not None, f"First call raised an exception for string_length={string_length}"
    assert result2 is not None, f"Second call raised an exception for string_length={string_length}"

    assert result1 == result2, \
        f"task_func is not deterministic with random.seed(0) for string_length={string_length}.\n" \
        f"First result: {result1}\nSecond result: {result2}"

@settings(max_examples=50, deadline=None)
@given(string_length=st.integers(min_value=0, max_value=12))
def test_keys_are_only_from_letters(string_length):
    """
    SPEC BASIS: "keys are letters and values are their frequencies". `LETTERS = ['a', 'b', 'c', 'd', 'e']`.
    PROPERTY: All keys in the returned OrderedDict must be present in the global LETTERS list.
              No other keys should be present.
    STRATEGY: Use string_length from 0 to 12. This ensures that the function doesn't accidentally introduce
              keys outside the specified alphabet.
    """
    random.seed(0) # Ensure reproducibility for internal random string generation
    try:
        result = task_func(string_length)
    except Exception:
        result = None

    assert result is not None, f"task_func raised an exception for string_length={string_length}"

    for key in result.keys():
        assert key in LETTERS, f"Key '{key}' found in output, but not in predefined LETTERS: {LETTERS}"